version: "3.4"

services:

  doctor-client:
    container_name: OpenPrescriptionDoctorClient
    network_mode: host
    build:
      context: ./doctor-client
      network: host
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      APP_SERVER_PORT: 3001
      API_HOST: http://localhost:3000
      API_KEY: YR4TBVHMBB4HJKEDB7DC25KV29A3RD6X
      APP_HOST: http://localhost:3001
      ORIGINALMY_API_URL: https://api1.originalmy.com
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./doctor-client/server:/home/node/openprescription/doctor-client/server
      - ./doctor-client/src:/home/node/openprescription/doctor-client/src
      - ./doctor-client/public:/home/node/openprescription/doctor-client/public
    command: npm run dev
  phamacy-client:
    container_name: OpenPrescriptionPharmacyClient
    network_mode: host
    build:
      context: ./pharmacy-client
      network: host
      dockerfile: Dockerfile
    environment:
      PORT: 4001
      APP_SERVER_PORT: 3002
      API_HOST: http://localhost:3000
      API_KEY: YR4TBVHMBB4HJKEDB7DC25KV29A3RD6X
      APP_HOST: http://localhost:3002
    expose:
      - 4001
    ports:
      - 4001:4001
    volumes:
      - ./pharmacy-client/server:/home/node/openprescription/pharmacy-client/server
      - ./pharmacy-client/src:/home/node/openprescription/pharmacy-client/src
      - ./pharmacy-client/public:/home/node/openprescription/pharmacy-client/public
    command: npm run dev
